// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: _test_jsonb.sql

package sqlcdb

import (
	"context"
)

const testJsonb = `-- name: TestJsonb :many
SELECT uri FROM all_bookmarks WHERE lower(tags_json)::jsonb ? $1
`

func (q *Queries) TestJsonb(ctx context.Context, tagsJson *string) ([]string, error) {
	rows, err := q.db.Query(ctx, testJsonb, tagsJson)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var uri string
		if err := rows.Scan(&uri); err != nil {
			return nil, err
		}
		items = append(items, uri)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
