// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToCollection = `-- name: AddToCollection :exec
INSERT INTO collection_items (uri, author_did, collection_uri, annotation_uri, position, created_at, indexed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT(uri) DO UPDATE SET
    position = EXCLUDED.position,
    indexed_at = EXCLUDED.indexed_at
`

type AddToCollectionParams struct {
	Uri           string      `json:"uri"`
	AuthorDid     string      `json:"authorDid"`
	CollectionUri string      `json:"collectionUri"`
	AnnotationUri string      `json:"annotationUri"`
	Position      pgtype.Int4 `json:"position"`
	CreatedAt     time.Time   `json:"createdAt"`
	IndexedAt     time.Time   `json:"indexedAt"`
}

func (q *Queries) AddToCollection(ctx context.Context, arg AddToCollectionParams) error {
	_, err := q.db.Exec(ctx, addToCollection,
		arg.Uri,
		arg.AuthorDid,
		arg.CollectionUri,
		arg.AnnotationUri,
		arg.Position,
		arg.CreatedAt,
		arg.IndexedAt,
	)
	return err
}

const createCollection = `-- name: CreateCollection :exec
INSERT INTO collections (uri, author_did, name, description, icon, created_at, indexed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT(uri) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    icon = EXCLUDED.icon,
    indexed_at = EXCLUDED.indexed_at
`

type CreateCollectionParams struct {
	Uri         string    `json:"uri"`
	AuthorDid   string    `json:"authorDid"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Icon        *string   `json:"icon"`
	CreatedAt   time.Time `json:"createdAt"`
	IndexedAt   time.Time `json:"indexedAt"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) error {
	_, err := q.db.Exec(ctx, createCollection,
		arg.Uri,
		arg.AuthorDid,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.CreatedAt,
		arg.IndexedAt,
	)
	return err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE uri = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, uri string) error {
	_, err := q.db.Exec(ctx, deleteCollection, uri)
	return err
}

const deleteCollectionItemsByCollection = `-- name: DeleteCollectionItemsByCollection :exec
DELETE FROM collection_items WHERE collection_uri = $1
`

func (q *Queries) DeleteCollectionItemsByCollection(ctx context.Context, collectionUri string) error {
	_, err := q.db.Exec(ctx, deleteCollectionItemsByCollection, collectionUri)
	return err
}

const getCollectionByURI = `-- name: GetCollectionByURI :one
SELECT uri, author_did, name, description, icon, created_at, indexed_at
FROM collections
WHERE uri = $1
`

func (q *Queries) GetCollectionByURI(ctx context.Context, uri string) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionByURI, uri)
	var i Collection
	err := row.Scan(
		&i.Uri,
		&i.AuthorDid,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
		&i.IndexedAt,
	)
	return i, err
}

const getCollectionItemCounts = `-- name: GetCollectionItemCounts :many
SELECT collection_uri, COUNT(*)
FROM collection_items
WHERE collection_uri = ANY($1::text[])
GROUP BY collection_uri
`

type GetCollectionItemCountsRow struct {
	CollectionUri string `json:"collectionUri"`
	Count         int64  `json:"count"`
}

func (q *Queries) GetCollectionItemCounts(ctx context.Context, dollar_1 []string) ([]GetCollectionItemCountsRow, error) {
	rows, err := q.db.Query(ctx, getCollectionItemCounts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCollectionItemCountsRow
	for rows.Next() {
		var i GetCollectionItemCountsRow
		if err := rows.Scan(&i.CollectionUri, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionItems = `-- name: GetCollectionItems :many
SELECT uri, author_did, collection_uri, annotation_uri, position, created_at, indexed_at
FROM collection_items
WHERE collection_uri = $1
ORDER BY position ASC, created_at DESC
`

func (q *Queries) GetCollectionItems(ctx context.Context, collectionUri string) ([]CollectionItem, error) {
	rows, err := q.db.Query(ctx, getCollectionItems, collectionUri)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionItem
	for rows.Next() {
		var i CollectionItem
		if err := rows.Scan(
			&i.Uri,
			&i.AuthorDid,
			&i.CollectionUri,
			&i.AnnotationUri,
			&i.Position,
			&i.CreatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionItemsByAuthor = `-- name: GetCollectionItemsByAuthor :many
SELECT uri, author_did, collection_uri, annotation_uri, position, created_at, indexed_at
FROM collection_items
WHERE author_did = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCollectionItemsByAuthor(ctx context.Context, authorDid string) ([]CollectionItem, error) {
	rows, err := q.db.Query(ctx, getCollectionItemsByAuthor, authorDid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionItem
	for rows.Next() {
		var i CollectionItem
		if err := rows.Scan(
			&i.Uri,
			&i.AuthorDid,
			&i.CollectionUri,
			&i.AnnotationUri,
			&i.Position,
			&i.CreatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionURIsForAnnotation = `-- name: GetCollectionURIsForAnnotation :many
SELECT collection_uri FROM collection_items WHERE annotation_uri = $1
`

func (q *Queries) GetCollectionURIsForAnnotation(ctx context.Context, annotationUri string) ([]string, error) {
	rows, err := q.db.Query(ctx, getCollectionURIsForAnnotation, annotationUri)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var collection_uri string
		if err := rows.Scan(&collection_uri); err != nil {
			return nil, err
		}
		items = append(items, collection_uri)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionsByAuthor = `-- name: GetCollectionsByAuthor :many
SELECT uri, author_did, name, description, icon, created_at, indexed_at
FROM collections
WHERE author_did = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCollectionsByAuthor(ctx context.Context, authorDid string) ([]Collection, error) {
	rows, err := q.db.Query(ctx, getCollectionsByAuthor, authorDid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.Uri,
			&i.AuthorDid,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionsByURIs = `-- name: GetCollectionsByURIs :many
SELECT uri, author_did, name, description, icon, created_at, indexed_at
FROM collections
WHERE uri = ANY($1::text[])
`

func (q *Queries) GetCollectionsByURIs(ctx context.Context, dollar_1 []string) ([]Collection, error) {
	rows, err := q.db.Query(ctx, getCollectionsByURIs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.Uri,
			&i.AuthorDid,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionsForNoteURIs = `-- name: GetCollectionsForNoteURIs :many
SELECT DISTINCT ON (ci.annotation_uri)
    ci.annotation_uri,
    c.uri, c.author_did, c.name, c.description, c.icon, c.created_at, c.indexed_at
FROM collection_items ci
JOIN collections c ON c.uri = ci.collection_uri
WHERE ci.annotation_uri = ANY($1::text[])
ORDER BY ci.annotation_uri, ci.created_at ASC
`

type GetCollectionsForNoteURIsRow struct {
	AnnotationUri string    `json:"annotationUri"`
	Uri           string    `json:"uri"`
	AuthorDid     string    `json:"authorDid"`
	Name          string    `json:"name"`
	Description   *string   `json:"description"`
	Icon          *string   `json:"icon"`
	CreatedAt     time.Time `json:"createdAt"`
	IndexedAt     time.Time `json:"indexedAt"`
}

func (q *Queries) GetCollectionsForNoteURIs(ctx context.Context, dollar_1 []string) ([]GetCollectionsForNoteURIsRow, error) {
	rows, err := q.db.Query(ctx, getCollectionsForNoteURIs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCollectionsForNoteURIsRow
	for rows.Next() {
		var i GetCollectionsForNoteURIsRow
		if err := rows.Scan(
			&i.AnnotationUri,
			&i.Uri,
			&i.AuthorDid,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPopularCollectionItems = `-- name: GetPopularCollectionItems :many
SELECT
    c.uri, c.author_did, c.collection_uri, c.annotation_uri,
    c.position, c.created_at, c.indexed_at
FROM collection_items c
LEFT JOIN LATERAL (
    SELECT COUNT(*) as cnt FROM likes WHERE subject_uri = c.annotation_uri
) l ON true
LEFT JOIN LATERAL (
    SELECT COUNT(*) as cnt FROM replies WHERE root_uri = c.annotation_uri
) r ON true
WHERE c.created_at > $1 AND (l.cnt + r.cnt) > 0
ORDER BY (l.cnt + r.cnt) DESC, c.created_at DESC
LIMIT $2 OFFSET $3
`

type GetPopularCollectionItemsParams struct {
	CreatedAt time.Time `json:"createdAt"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) GetPopularCollectionItems(ctx context.Context, arg GetPopularCollectionItemsParams) ([]CollectionItem, error) {
	rows, err := q.db.Query(ctx, getPopularCollectionItems, arg.CreatedAt, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionItem
	for rows.Next() {
		var i CollectionItem
		if err := rows.Scan(
			&i.Uri,
			&i.AuthorDid,
			&i.CollectionUri,
			&i.AnnotationUri,
			&i.Position,
			&i.CreatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentCollectionItems = `-- name: GetRecentCollectionItems :many
SELECT uri, author_did, collection_uri, annotation_uri, position, created_at, indexed_at
FROM collection_items
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetRecentCollectionItemsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetRecentCollectionItems(ctx context.Context, arg GetRecentCollectionItemsParams) ([]CollectionItem, error) {
	rows, err := q.db.Query(ctx, getRecentCollectionItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionItem
	for rows.Next() {
		var i CollectionItem
		if err := rows.Scan(
			&i.Uri,
			&i.AuthorDid,
			&i.CollectionUri,
			&i.AnnotationUri,
			&i.Position,
			&i.CreatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShelvedCollectionItems = `-- name: GetShelvedCollectionItems :many
SELECT
    c.uri, c.author_did, c.collection_uri, c.annotation_uri,
    c.position, c.created_at, c.indexed_at
FROM collection_items c
WHERE c.created_at < $1 AND c.created_at > $2
    AND NOT EXISTS (SELECT 1 FROM likes WHERE subject_uri = c.annotation_uri)
    AND NOT EXISTS (SELECT 1 FROM replies WHERE root_uri = c.annotation_uri)
ORDER BY RANDOM()
LIMIT $3 OFFSET $4
`

type GetShelvedCollectionItemsParams struct {
	CreatedAt   time.Time `json:"createdAt"`
	CreatedAt_2 time.Time `json:"createdAt2"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) GetShelvedCollectionItems(ctx context.Context, arg GetShelvedCollectionItemsParams) ([]CollectionItem, error) {
	rows, err := q.db.Query(ctx, getShelvedCollectionItems,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionItem
	for rows.Next() {
		var i CollectionItem
		if err := rows.Scan(
			&i.Uri,
			&i.AuthorDid,
			&i.CollectionUri,
			&i.AnnotationUri,
			&i.Position,
			&i.CreatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromCollection = `-- name: RemoveFromCollection :exec
DELETE FROM collection_items WHERE uri = $1
`

func (q *Queries) RemoveFromCollection(ctx context.Context, uri string) error {
	_, err := q.db.Exec(ctx, removeFromCollection, uri)
	return err
}
