// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package sqlcdb

import (
	"context"
	"time"
)

const getEditHistory = `-- name: GetEditHistory :many
SELECT id, uri, record_type, previous_content, previous_cid, edited_at
FROM edit_history
WHERE uri = $1
ORDER BY edited_at DESC
`

func (q *Queries) GetEditHistory(ctx context.Context, uri string) ([]EditHistory, error) {
	rows, err := q.db.Query(ctx, getEditHistory, uri)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EditHistory
	for rows.Next() {
		var i EditHistory
		if err := rows.Scan(
			&i.ID,
			&i.Uri,
			&i.RecordType,
			&i.PreviousContent,
			&i.PreviousCid,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestEditTimes = `-- name: GetLatestEditTimes :many
SELECT uri, MAX(edited_at) as edited_at
FROM edit_history
WHERE uri = ANY($1::text[])
GROUP BY uri
`

type GetLatestEditTimesRow struct {
	Uri      string      `json:"uri"`
	EditedAt interface{} `json:"editedAt"`
}

func (q *Queries) GetLatestEditTimes(ctx context.Context, dollar_1 []string) ([]GetLatestEditTimesRow, error) {
	rows, err := q.db.Query(ctx, getLatestEditTimes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestEditTimesRow
	for rows.Next() {
		var i GetLatestEditTimesRow
		if err := rows.Scan(&i.Uri, &i.EditedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveEditHistory = `-- name: SaveEditHistory :exec
INSERT INTO edit_history (uri, record_type, previous_content, previous_cid, edited_at)
VALUES ($1, $2, $3, $4, $5)
`

type SaveEditHistoryParams struct {
	Uri             string    `json:"uri"`
	RecordType      string    `json:"recordType"`
	PreviousContent string    `json:"previousContent"`
	PreviousCid     *string   `json:"previousCid"`
	EditedAt        time.Time `json:"editedAt"`
}

func (q *Queries) SaveEditHistory(ctx context.Context, arg SaveEditHistoryParams) error {
	_, err := q.db.Exec(ctx, saveEditHistory,
		arg.Uri,
		arg.RecordType,
		arg.PreviousContent,
		arg.PreviousCid,
		arg.EditedAt,
	)
	return err
}
