// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kv.sql

package sqlcdb

import (
	"context"
)

const getKVValue = `-- name: GetKVValue :one
SELECT value FROM kv_store WHERE key = $1
`

func (q *Queries) GetKVValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getKVValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertKVIgnore = `-- name: InsertKVIgnore :exec
INSERT INTO kv_store (key, value, updated_at) VALUES ($1, $2, NOW()) ON CONFLICT (key) DO NOTHING
`

type InsertKVIgnoreParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) InsertKVIgnore(ctx context.Context, arg InsertKVIgnoreParams) error {
	_, err := q.db.Exec(ctx, insertKVIgnore, arg.Key, arg.Value)
	return err
}
