// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: likes.sql

package sqlcdb

import (
	"context"
	"time"
)

const createLike = `-- name: CreateLike :exec
INSERT INTO likes (uri, author_did, subject_uri, created_at, indexed_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT(uri) DO NOTHING
`

type CreateLikeParams struct {
	Uri        string    `json:"uri"`
	AuthorDid  string    `json:"authorDid"`
	SubjectUri string    `json:"subjectUri"`
	CreatedAt  time.Time `json:"createdAt"`
	IndexedAt  time.Time `json:"indexedAt"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) error {
	_, err := q.db.Exec(ctx, createLike,
		arg.Uri,
		arg.AuthorDid,
		arg.SubjectUri,
		arg.CreatedAt,
		arg.IndexedAt,
	)
	return err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM likes WHERE uri = $1
`

func (q *Queries) DeleteLike(ctx context.Context, uri string) error {
	_, err := q.db.Exec(ctx, deleteLike, uri)
	return err
}

const getLikeByUserAndSubject = `-- name: GetLikeByUserAndSubject :one
SELECT uri, author_did, subject_uri, created_at, indexed_at
FROM likes
WHERE author_did = $1 AND subject_uri = $2
`

type GetLikeByUserAndSubjectParams struct {
	AuthorDid  string `json:"authorDid"`
	SubjectUri string `json:"subjectUri"`
}

func (q *Queries) GetLikeByUserAndSubject(ctx context.Context, arg GetLikeByUserAndSubjectParams) (Like, error) {
	row := q.db.QueryRow(ctx, getLikeByUserAndSubject, arg.AuthorDid, arg.SubjectUri)
	var i Like
	err := row.Scan(
		&i.Uri,
		&i.AuthorDid,
		&i.SubjectUri,
		&i.CreatedAt,
		&i.IndexedAt,
	)
	return i, err
}

const getLikeCount = `-- name: GetLikeCount :one
SELECT COUNT(*) FROM likes WHERE subject_uri = $1
`

func (q *Queries) GetLikeCount(ctx context.Context, subjectUri string) (int64, error) {
	row := q.db.QueryRow(ctx, getLikeCount, subjectUri)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLikeCounts = `-- name: GetLikeCounts :many
SELECT subject_uri, COUNT(*)
FROM likes
WHERE subject_uri = ANY($1::text[])
GROUP BY subject_uri
`

type GetLikeCountsRow struct {
	SubjectUri string `json:"subjectUri"`
	Count      int64  `json:"count"`
}

func (q *Queries) GetLikeCounts(ctx context.Context, dollar_1 []string) ([]GetLikeCountsRow, error) {
	rows, err := q.db.Query(ctx, getLikeCounts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLikeCountsRow
	for rows.Next() {
		var i GetLikeCountsRow
		if err := rows.Scan(&i.SubjectUri, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLikesByAuthor = `-- name: GetLikesByAuthor :many
SELECT uri, author_did, subject_uri, created_at, indexed_at
FROM likes
WHERE author_did = $1
ORDER BY created_at DESC
`

func (q *Queries) GetLikesByAuthor(ctx context.Context, authorDid string) ([]Like, error) {
	rows, err := q.db.Query(ctx, getLikesByAuthor, authorDid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Like
	for rows.Next() {
		var i Like
		if err := rows.Scan(
			&i.Uri,
			&i.AuthorDid,
			&i.SubjectUri,
			&i.CreatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getViewerLikes = `-- name: GetViewerLikes :many
SELECT subject_uri
FROM likes
WHERE author_did = $1 AND subject_uri = ANY($2::text[])
`

type GetViewerLikesParams struct {
	AuthorDid string   `json:"authorDid"`
	Column2   []string `json:"column2"`
}

func (q *Queries) GetViewerLikes(ctx context.Context, arg GetViewerLikesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getViewerLikes, arg.AuthorDid, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var subject_uri string
		if err := rows.Scan(&subject_uri); err != nil {
			return nil, err
		}
		items = append(items, subject_uri)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
