// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AllAnnotation struct {
	Uri          string    `json:"uri"`
	AuthorDid    string    `json:"authorDid"`
	Motivation   *string   `json:"motivation"`
	BodyValue    *string   `json:"bodyValue"`
	BodyFormat   *string   `json:"bodyFormat"`
	BodyUri      *string   `json:"bodyUri"`
	TargetSource *string   `json:"targetSource"`
	TargetHash   *string   `json:"targetHash"`
	TargetTitle  *string   `json:"targetTitle"`
	SelectorJson *string   `json:"selectorJson"`
	TagsJson     *string   `json:"tagsJson"`
	CreatedAt    time.Time `json:"createdAt"`
	IndexedAt    time.Time `json:"indexedAt"`
	Cid          *string   `json:"cid"`
}

type AllBookmark struct {
	Uri         string    `json:"uri"`
	AuthorDid   string    `json:"authorDid"`
	Source      string    `json:"source"`
	SourceHash  string    `json:"sourceHash"`
	Title       *string   `json:"title"`
	Description *string   `json:"description"`
	TagsJson    *string   `json:"tagsJson"`
	CreatedAt   time.Time `json:"createdAt"`
	IndexedAt   time.Time `json:"indexedAt"`
	Cid         *string   `json:"cid"`
}

type AllHighlight struct {
	Uri          string    `json:"uri"`
	AuthorDid    string    `json:"authorDid"`
	TargetSource string    `json:"targetSource"`
	TargetHash   string    `json:"targetHash"`
	TargetTitle  *string   `json:"targetTitle"`
	SelectorJson *string   `json:"selectorJson"`
	Color        *string   `json:"color"`
	TagsJson     *string   `json:"tagsJson"`
	CreatedAt    time.Time `json:"createdAt"`
	IndexedAt    time.Time `json:"indexedAt"`
	Cid          *string   `json:"cid"`
}

type Annotation struct {
	Uri          string    `json:"uri"`
	AuthorDid    string    `json:"authorDid"`
	Motivation   *string   `json:"motivation"`
	BodyValue    *string   `json:"bodyValue"`
	BodyFormat   *string   `json:"bodyFormat"`
	BodyUri      *string   `json:"bodyUri"`
	TargetSource *string   `json:"targetSource"`
	TargetHash   *string   `json:"targetHash"`
	TargetTitle  *string   `json:"targetTitle"`
	SelectorJson *string   `json:"selectorJson"`
	TagsJson     *string   `json:"tagsJson"`
	CreatedAt    time.Time `json:"createdAt"`
	IndexedAt    time.Time `json:"indexedAt"`
	Cid          *string   `json:"cid"`
}

type AnnotationEmbedding struct {
	AnnotationUri string    `json:"annotationUri"`
	AuthorDid     string    `json:"authorDid"`
	DocumentUri   *string   `json:"documentUri"`
	Embedding     string    `json:"embedding"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type ApiKey struct {
	ID         string     `json:"id"`
	OwnerDid   string     `json:"ownerDid"`
	Name       string     `json:"name"`
	KeyHash    string     `json:"keyHash"`
	CreatedAt  time.Time  `json:"createdAt"`
	LastUsedAt *time.Time `json:"lastUsedAt"`
	Uri        *string    `json:"uri"`
	Cid        *string    `json:"cid"`
	IndexedAt  *time.Time `json:"indexedAt"`
}

type BannedAccount struct {
	Did      string    `json:"did"`
	Reason   *string   `json:"reason"`
	BannedBy string    `json:"bannedBy"`
	BannedAt time.Time `json:"bannedAt"`
}

type Block struct {
	ID         int32     `json:"id"`
	ActorDid   string    `json:"actorDid"`
	SubjectDid string    `json:"subjectDid"`
	CreatedAt  time.Time `json:"createdAt"`
}

type Bookmark struct {
	Uri         string    `json:"uri"`
	AuthorDid   string    `json:"authorDid"`
	Source      string    `json:"source"`
	SourceHash  string    `json:"sourceHash"`
	Title       *string   `json:"title"`
	Description *string   `json:"description"`
	TagsJson    *string   `json:"tagsJson"`
	CreatedAt   time.Time `json:"createdAt"`
	IndexedAt   time.Time `json:"indexedAt"`
	Cid         *string   `json:"cid"`
}

type Collection struct {
	Uri         string    `json:"uri"`
	AuthorDid   string    `json:"authorDid"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Icon        *string   `json:"icon"`
	CreatedAt   time.Time `json:"createdAt"`
	IndexedAt   time.Time `json:"indexedAt"`
}

type CollectionItem struct {
	Uri           string      `json:"uri"`
	AuthorDid     string      `json:"authorDid"`
	CollectionUri string      `json:"collectionUri"`
	AnnotationUri string      `json:"annotationUri"`
	Position      pgtype.Int4 `json:"position"`
	CreatedAt     time.Time   `json:"createdAt"`
	IndexedAt     time.Time   `json:"indexedAt"`
}

type CommunityBookmarkRef struct {
	NoteUri      string `json:"noteUri"`
	CommunityUri string `json:"communityUri"`
}

type ContentLabel struct {
	ID        int32     `json:"id"`
	Src       string    `json:"src"`
	Uri       string    `json:"uri"`
	Val       string    `json:"val"`
	Neg       int32     `json:"neg"`
	CreatedBy string    `json:"createdBy"`
	CreatedAt time.Time `json:"createdAt"`
}

type Cursor struct {
	ID         string    `json:"id"`
	LastCursor int64     `json:"lastCursor"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type Document struct {
	Uri          string    `json:"uri"`
	AuthorDid    string    `json:"authorDid"`
	Site         string    `json:"site"`
	Path         *string   `json:"path"`
	Title        string    `json:"title"`
	Description  *string   `json:"description"`
	TextContent  *string   `json:"textContent"`
	TagsJson     *string   `json:"tagsJson"`
	CanonicalUrl *string   `json:"canonicalUrl"`
	PublishedAt  time.Time `json:"publishedAt"`
	IndexedAt    time.Time `json:"indexedAt"`
}

type DocumentEmbedding struct {
	DocumentUri string    `json:"documentUri"`
	Embedding   string    `json:"embedding"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type EditHistory struct {
	ID              int32     `json:"id"`
	Uri             string    `json:"uri"`
	RecordType      string    `json:"recordType"`
	PreviousContent string    `json:"previousContent"`
	PreviousCid     *string   `json:"previousCid"`
	EditedAt        time.Time `json:"editedAt"`
}

type Highlight struct {
	Uri          string    `json:"uri"`
	AuthorDid    string    `json:"authorDid"`
	TargetSource string    `json:"targetSource"`
	TargetHash   string    `json:"targetHash"`
	TargetTitle  *string   `json:"targetTitle"`
	SelectorJson *string   `json:"selectorJson"`
	Color        *string   `json:"color"`
	TagsJson     *string   `json:"tagsJson"`
	CreatedAt    time.Time `json:"createdAt"`
	IndexedAt    time.Time `json:"indexedAt"`
	Cid          *string   `json:"cid"`
}

type KvStore struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Like struct {
	Uri        string    `json:"uri"`
	AuthorDid  string    `json:"authorDid"`
	SubjectUri string    `json:"subjectUri"`
	CreatedAt  time.Time `json:"createdAt"`
	IndexedAt  time.Time `json:"indexedAt"`
}

type ModerationAction struct {
	ID        int32     `json:"id"`
	ReportID  int32     `json:"reportId"`
	ActorDid  string    `json:"actorDid"`
	Action    string    `json:"action"`
	Comment   *string   `json:"comment"`
	CreatedAt time.Time `json:"createdAt"`
}

type ModerationReport struct {
	ID          int32      `json:"id"`
	ReporterDid string     `json:"reporterDid"`
	SubjectDid  string     `json:"subjectDid"`
	SubjectUri  *string    `json:"subjectUri"`
	ReasonType  string     `json:"reasonType"`
	ReasonText  *string    `json:"reasonText"`
	Status      string     `json:"status"`
	CreatedAt   time.Time  `json:"createdAt"`
	ResolvedAt  *time.Time `json:"resolvedAt"`
	ResolvedBy  *string    `json:"resolvedBy"`
}

type Mute struct {
	ID         int32     `json:"id"`
	ActorDid   string    `json:"actorDid"`
	SubjectDid string    `json:"subjectDid"`
	CreatedAt  time.Time `json:"createdAt"`
}

type Note struct {
	Uri          string    `json:"uri"`
	AuthorDid    string    `json:"authorDid"`
	Motivation   *string   `json:"motivation"`
	Color        *string   `json:"color"`
	Description  *string   `json:"description"`
	BodyValue    *string   `json:"bodyValue"`
	BodyFormat   *string   `json:"bodyFormat"`
	BodyUri      *string   `json:"bodyUri"`
	TargetSource string    `json:"targetSource"`
	TargetHash   string    `json:"targetHash"`
	TargetTitle  *string   `json:"targetTitle"`
	SelectorJson *string   `json:"selectorJson"`
	TagsJson     *string   `json:"tagsJson"`
	CreatedAt    time.Time `json:"createdAt"`
	IndexedAt    time.Time `json:"indexedAt"`
	Cid          *string   `json:"cid"`
}

type Notification struct {
	ID           int32      `json:"id"`
	RecipientDid string     `json:"recipientDid"`
	ActorDid     string     `json:"actorDid"`
	Type         string     `json:"type"`
	SubjectUri   string     `json:"subjectUri"`
	CreatedAt    time.Time  `json:"createdAt"`
	ReadAt       *time.Time `json:"readAt"`
}

type OauthPendingAuth struct {
	State         string             `json:"state"`
	Did           string             `json:"did"`
	Handle        string             `json:"handle"`
	Pds           string             `json:"pds"`
	Issuer        string             `json:"issuer"`
	TokenEndpoint string             `json:"tokenEndpoint"`
	PkceVerifier  string             `json:"pkceVerifier"`
	DpopCrv       string             `json:"dpopCrv"`
	DpopD         string             `json:"dpopD"`
	DpopX         string             `json:"dpopX"`
	DpopY         string             `json:"dpopY"`
	DpopNonce     string             `json:"dpopNonce"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
}

type OauthSession struct {
	ID                   string             `json:"id"`
	Did                  string             `json:"did"`
	Handle               string             `json:"handle"`
	Pds                  string             `json:"pds"`
	Email                string             `json:"email"`
	AccessToken          string             `json:"accessToken"`
	RefreshToken         string             `json:"refreshToken"`
	TokenEndpoint        string             `json:"tokenEndpoint"`
	Issuer               string             `json:"issuer"`
	DpopCrv              string             `json:"dpopCrv"`
	DpopD                string             `json:"dpopD"`
	DpopX                string             `json:"dpopX"`
	DpopY                string             `json:"dpopY"`
	AccessTokenExpiresAt pgtype.Timestamptz `json:"accessTokenExpiresAt"`
	ExpiresAt            pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt            pgtype.Timestamptz `json:"createdAt"`
}

type PendingAuth struct {
	State        string    `json:"state"`
	Did          string    `json:"did"`
	Handle       string    `json:"handle"`
	Pds          string    `json:"pds"`
	AuthServer   string    `json:"authServer"`
	Issuer       string    `json:"issuer"`
	PkceVerifier string    `json:"pkceVerifier"`
	DpopKeyPem   string    `json:"dpopKeyPem"`
	DpopNonce    string    `json:"dpopNonce"`
	CreatedAt    time.Time `json:"createdAt"`
}

type Preference struct {
	Uri                          string      `json:"uri"`
	AuthorDid                    string      `json:"authorDid"`
	ExternalLinkSkippedHostnames *string     `json:"externalLinkSkippedHostnames"`
	SubscribedLabelers           *string     `json:"subscribedLabelers"`
	LabelPreferences             *string     `json:"labelPreferences"`
	DisableExternalLinkWarning   pgtype.Bool `json:"disableExternalLinkWarning"`
	EnableCommunityBookmarks     pgtype.Bool `json:"enableCommunityBookmarks"`
	CreatedAt                    time.Time   `json:"createdAt"`
	IndexedAt                    time.Time   `json:"indexedAt"`
	Cid                          *string     `json:"cid"`
}

type Profile struct {
	Uri         string    `json:"uri"`
	AuthorDid   string    `json:"authorDid"`
	DisplayName *string   `json:"displayName"`
	Avatar      *string   `json:"avatar"`
	Bio         *string   `json:"bio"`
	Website     *string   `json:"website"`
	LinksJson   *string   `json:"linksJson"`
	CreatedAt   time.Time `json:"createdAt"`
	IndexedAt   time.Time `json:"indexedAt"`
	Cid         *string   `json:"cid"`
}

type Publication struct {
	Uri            string    `json:"uri"`
	AuthorDid      string    `json:"authorDid"`
	Url            string    `json:"url"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
	ShowInDiscover bool      `json:"showInDiscover"`
	IndexedAt      time.Time `json:"indexedAt"`
}

type Reply struct {
	Uri       string    `json:"uri"`
	AuthorDid string    `json:"authorDid"`
	ParentUri string    `json:"parentUri"`
	RootUri   string    `json:"rootUri"`
	Text      string    `json:"text"`
	Format    *string   `json:"format"`
	CreatedAt time.Time `json:"createdAt"`
	IndexedAt time.Time `json:"indexedAt"`
	Cid       *string   `json:"cid"`
}

type Session struct {
	ID           string    `json:"id"`
	Did          string    `json:"did"`
	Handle       string    `json:"handle"`
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	DpopKey      *string   `json:"dpopKey"`
	CreatedAt    time.Time `json:"createdAt"`
	ExpiresAt    time.Time `json:"expiresAt"`
}

type TakenDownUri struct {
	Uri         string    `json:"uri"`
	TakenDownAt time.Time `json:"takenDownAt"`
}

type UserProfile struct {
	AuthorDid       string    `json:"authorDid"`
	Embedding       string    `json:"embedding"`
	TagAffinities   *string   `json:"tagAffinities"`
	AnnotationCount int32     `json:"annotationCount"`
	UpdatedAt       time.Time `json:"updatedAt"`
}
