// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddToCollection(ctx context.Context, arg AddToCollectionParams) error
	BanAccount(ctx context.Context, arg BanAccountParams) error
	CommunityBookmarkExists(ctx context.Context, arg CommunityBookmarkExistsParams) (int32, error)
	CountOAuthSessionsByDID(ctx context.Context, did string) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error
	CreateAnnotation(ctx context.Context, arg CreateAnnotationParams) error
	CreateBlock(ctx context.Context, arg CreateBlockParams) error
	CreateBookmark(ctx context.Context, arg CreateBookmarkParams) error
	CreateCollection(ctx context.Context, arg CreateCollectionParams) error
	CreateContentLabel(ctx context.Context, arg CreateContentLabelParams) error
	CreateHighlight(ctx context.Context, arg CreateHighlightParams) error
	CreateLike(ctx context.Context, arg CreateLikeParams) error
	CreateModerationAction(ctx context.Context, arg CreateModerationActionParams) error
	CreateMute(ctx context.Context, arg CreateMuteParams) error
	CreateNote(ctx context.Context, arg CreateNoteParams) error
	CreateNotification(ctx context.Context, arg CreateNotificationParams) error
	CreateOAuthSession(ctx context.Context, arg CreateOAuthSessionParams) error
	CreateReply(ctx context.Context, arg CreateReplyParams) error
	CreateReport(ctx context.Context, arg CreateReportParams) (int32, error)
	DeleteAPIKeyByURI(ctx context.Context, uri *string) error
	DeleteAPIKeyReturningURI(ctx context.Context, arg DeleteAPIKeyReturningURIParams) (*string, error)
	DeleteAnnotation(ctx context.Context, uri string) error
	DeleteAnnotationEmbedding(ctx context.Context, annotationUri string) error
	DeleteBlock(ctx context.Context, arg DeleteBlockParams) error
	DeleteBookmark(ctx context.Context, uri string) error
	DeleteCollection(ctx context.Context, uri string) error
	DeleteCollectionItemsByCollection(ctx context.Context, collectionUri string) error
	DeleteCommunityBookmarkRef(ctx context.Context, noteUri string) error
	DeleteContentLabel(ctx context.Context, id int32) error
	DeleteDocument(ctx context.Context, uri string) error
	DeleteExpiredOAuthSessions(ctx context.Context) error
	DeleteExpiredPendingAuthsOAuth(ctx context.Context, createdAt pgtype.Timestamptz) error
	DeleteHighlight(ctx context.Context, uri string) error
	DeleteLike(ctx context.Context, uri string) error
	DeleteMute(ctx context.Context, arg DeleteMuteParams) error
	DeleteNote(ctx context.Context, uri string) error
	DeleteOAuthSession(ctx context.Context, id string) error
	DeleteOAuthSessionsByDID(ctx context.Context, did string) error
	DeletePendingAuthOAuth(ctx context.Context, state string) error
	DeletePreferences(ctx context.Context, uri string) error
	DeleteProfile(ctx context.Context, uri string) error
	DeletePublication(ctx context.Context, uri string) error
	DeleteReply(ctx context.Context, uri string) error
	DeleteSelfLabels(ctx context.Context, arg DeleteSelfLabelsParams) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error)
	GetAPIKeyURIs(ctx context.Context, ownerDid string) ([]*string, error)
	GetAPIKeysByOwner(ctx context.Context, ownerDid string) ([]GetAPIKeysByOwnerRow, error)
	GetAllContentLabels(ctx context.Context, arg GetAllContentLabelsParams) ([]ContentLabel, error)
	GetAnnotationAuthorByURI(ctx context.Context, uri string) (string, error)
	GetAnnotationByURI(ctx context.Context, uri string) (AllAnnotation, error)
	GetAnnotationEmbeddingsByAuthor(ctx context.Context, authorDid string) ([]AnnotationEmbedding, error)
	GetAnnotationURIs(ctx context.Context, authorDid string) ([]string, error)
	GetAnnotationsByAuthor(ctx context.Context, arg GetAnnotationsByAuthorParams) ([]AllAnnotation, error)
	GetAnnotationsByAuthorAndTargetHash(ctx context.Context, arg GetAnnotationsByAuthorAndTargetHashParams) ([]AllAnnotation, error)
	GetAnnotationsByMotivation(ctx context.Context, arg GetAnnotationsByMotivationParams) ([]AllAnnotation, error)
	GetAnnotationsByTag(ctx context.Context, arg GetAnnotationsByTagParams) ([]AllAnnotation, error)
	GetAnnotationsByTagAndAuthor(ctx context.Context, arg GetAnnotationsByTagAndAuthorParams) ([]AllAnnotation, error)
	GetAnnotationsByTargetHash(ctx context.Context, arg GetAnnotationsByTargetHashParams) ([]AllAnnotation, error)
	GetAnnotationsByURIs(ctx context.Context, dollar_1 []string) ([]AllAnnotation, error)
	GetAnnotationsWithoutEmbeddings(ctx context.Context, limit int32) ([]Annotation, error)
	GetBannedAccounts(ctx context.Context) ([]BannedAccount, error)
	GetBannedDIDs(ctx context.Context) ([]string, error)
	GetBlockedByDIDs(ctx context.Context, subjectDid string) ([]string, error)
	GetBlockedDIDs(ctx context.Context, actorDid string) ([]string, error)
	GetBlocks(ctx context.Context, actorDid string) ([]Block, error)
	GetBookmarkAuthorByURI(ctx context.Context, uri string) (string, error)
	GetBookmarkByURI(ctx context.Context, uri string) (AllBookmark, error)
	GetBookmarkURIs(ctx context.Context, authorDid string) ([]string, error)
	GetBookmarksByAuthor(ctx context.Context, arg GetBookmarksByAuthorParams) ([]AllBookmark, error)
	GetBookmarksByTag(ctx context.Context, arg GetBookmarksByTagParams) ([]AllBookmark, error)
	GetBookmarksByTagAndAuthor(ctx context.Context, arg GetBookmarksByTagAndAuthorParams) ([]AllBookmark, error)
	GetBookmarksByTargetHash(ctx context.Context, arg GetBookmarksByTargetHashParams) ([]AllBookmark, error)
	GetBookmarksByURIs(ctx context.Context, dollar_1 []string) ([]AllBookmark, error)
	GetCandidateDocuments(ctx context.Context, arg GetCandidateDocumentsParams) ([]GetCandidateDocumentsRow, error)
	GetCollectionByURI(ctx context.Context, uri string) (Collection, error)
	GetCollectionItemCounts(ctx context.Context, dollar_1 []string) ([]GetCollectionItemCountsRow, error)
	GetCollectionItems(ctx context.Context, collectionUri string) ([]CollectionItem, error)
	GetCollectionItemsByAuthor(ctx context.Context, authorDid string) ([]CollectionItem, error)
	GetCollectionURIsForAnnotation(ctx context.Context, annotationUri string) ([]string, error)
	GetCollectionsByAuthor(ctx context.Context, authorDid string) ([]Collection, error)
	GetCollectionsByURIs(ctx context.Context, dollar_1 []string) ([]Collection, error)
	GetCollectionsForNoteURIs(ctx context.Context, dollar_1 []string) ([]GetCollectionsForNoteURIsRow, error)
	GetCommunityBookmarkURI(ctx context.Context, noteUri string) (string, error)
	GetContentLabelsForURIs(ctx context.Context, dollar_1 []string) ([]ContentLabel, error)
	GetContentLabelsForURIsBySrc(ctx context.Context, arg GetContentLabelsForURIsBySrcParams) ([]ContentLabel, error)
	GetDistinctAnnotationAuthors(ctx context.Context) ([]string, error)
	GetDocumentByCanonicalURL(ctx context.Context, canonicalUrl *string) (Document, error)
	GetDocumentByURI(ctx context.Context, uri string) (Document, error)
	GetDocumentCount(ctx context.Context) (int64, error)
	GetDocumentsWithoutEmbeddings(ctx context.Context, limit int32) ([]Document, error)
	GetEditHistory(ctx context.Context, uri string) ([]EditHistory, error)
	GetHighlightAuthorByURI(ctx context.Context, uri string) (string, error)
	GetHighlightByURI(ctx context.Context, uri string) (AllHighlight, error)
	GetHighlightURIs(ctx context.Context, authorDid string) ([]string, error)
	GetHighlightsByAuthor(ctx context.Context, arg GetHighlightsByAuthorParams) ([]AllHighlight, error)
	GetHighlightsByAuthorAndTargetHash(ctx context.Context, arg GetHighlightsByAuthorAndTargetHashParams) ([]AllHighlight, error)
	GetHighlightsByTag(ctx context.Context, arg GetHighlightsByTagParams) ([]AllHighlight, error)
	GetHighlightsByTagAndAuthor(ctx context.Context, arg GetHighlightsByTagAndAuthorParams) ([]AllHighlight, error)
	GetHighlightsByTargetHash(ctx context.Context, arg GetHighlightsByTargetHashParams) ([]AllHighlight, error)
	GetHighlightsByURIs(ctx context.Context, dollar_1 []string) ([]AllHighlight, error)
	GetHighlightsWithoutEmbeddings(ctx context.Context, limit int32) ([]GetHighlightsWithoutEmbeddingsRow, error)
	GetKVValue(ctx context.Context, key string) (string, error)
	GetLatestEditTimes(ctx context.Context, dollar_1 []string) ([]GetLatestEditTimesRow, error)
	GetLatestOAuthSessionByDID(ctx context.Context, did string) (OauthSession, error)
	GetLikeByUserAndSubject(ctx context.Context, arg GetLikeByUserAndSubjectParams) (Like, error)
	GetLikeCount(ctx context.Context, subjectUri string) (int64, error)
	GetLikeCounts(ctx context.Context, dollar_1 []string) ([]GetLikeCountsRow, error)
	GetLikesByAuthor(ctx context.Context, authorDid string) ([]Like, error)
	GetMarginAnnotations(ctx context.Context, arg GetMarginAnnotationsParams) ([]AllAnnotation, error)
	GetMarginAnnotationsByAuthor(ctx context.Context, arg GetMarginAnnotationsByAuthorParams) ([]AllAnnotation, error)
	GetMarginAnnotationsByTag(ctx context.Context, arg GetMarginAnnotationsByTagParams) ([]AllAnnotation, error)
	GetMarginAnnotationsByTagAndAuthor(ctx context.Context, arg GetMarginAnnotationsByTagAndAuthorParams) ([]AllAnnotation, error)
	GetMarginBookmarks(ctx context.Context, arg GetMarginBookmarksParams) ([]AllBookmark, error)
	GetMarginBookmarksByAuthor(ctx context.Context, arg GetMarginBookmarksByAuthorParams) ([]AllBookmark, error)
	GetMarginBookmarksByTag(ctx context.Context, arg GetMarginBookmarksByTagParams) ([]AllBookmark, error)
	GetMarginBookmarksByTagAndAuthor(ctx context.Context, arg GetMarginBookmarksByTagAndAuthorParams) ([]AllBookmark, error)
	GetMarginHighlights(ctx context.Context, arg GetMarginHighlightsParams) ([]AllHighlight, error)
	GetMarginHighlightsByAuthor(ctx context.Context, arg GetMarginHighlightsByAuthorParams) ([]AllHighlight, error)
	GetMarginHighlightsByTag(ctx context.Context, arg GetMarginHighlightsByTagParams) ([]AllHighlight, error)
	GetMarginHighlightsByTagAndAuthor(ctx context.Context, arg GetMarginHighlightsByTagAndAuthorParams) ([]AllHighlight, error)
	GetMutedDIDs(ctx context.Context, actorDid string) ([]string, error)
	GetMutes(ctx context.Context, actorDid string) ([]Mute, error)
	GetNoteByURI(ctx context.Context, uri string) (Note, error)
	GetNotesByURIs(ctx context.Context, dollar_1 []string) ([]Note, error)
	GetNotifications(ctx context.Context, arg GetNotificationsParams) ([]Notification, error)
	GetOAuthSessionByID(ctx context.Context, id string) (GetOAuthSessionByIDRow, error)
	GetOrphanedRepliesByAuthor(ctx context.Context, authorDid string) ([]Reply, error)
	GetPendingAuthOAuth(ctx context.Context, state string) (GetPendingAuthOAuthRow, error)
	GetPopularAnnotations(ctx context.Context, arg GetPopularAnnotationsParams) ([]AllAnnotation, error)
	GetPopularBookmarks(ctx context.Context, arg GetPopularBookmarksParams) ([]AllBookmark, error)
	GetPopularCollectionItems(ctx context.Context, arg GetPopularCollectionItemsParams) ([]CollectionItem, error)
	GetPopularDocuments(ctx context.Context, arg GetPopularDocumentsParams) ([]Document, error)
	GetPopularHighlights(ctx context.Context, arg GetPopularHighlightsParams) ([]AllHighlight, error)
	GetPreferenceURIs(ctx context.Context, authorDid string) ([]string, error)
	GetPreferences(ctx context.Context, authorDid string) (Preference, error)
	GetProfile(ctx context.Context, authorDid string) (GetProfileRow, error)
	GetProfilesByDIDs(ctx context.Context, dollar_1 []string) ([]GetProfilesByDIDsRow, error)
	GetPublicationByURL(ctx context.Context, url string) (Publication, error)
	GetRecentAnnotationEmbeddingsByAuthor(ctx context.Context, arg GetRecentAnnotationEmbeddingsByAuthorParams) ([]AnnotationEmbedding, error)
	GetRecentAnnotations(ctx context.Context, arg GetRecentAnnotationsParams) ([]AllAnnotation, error)
	GetRecentBookmarks(ctx context.Context, arg GetRecentBookmarksParams) ([]AllBookmark, error)
	GetRecentCollectionItems(ctx context.Context, arg GetRecentCollectionItemsParams) ([]CollectionItem, error)
	GetRecentDocuments(ctx context.Context, arg GetRecentDocumentsParams) ([]Document, error)
	GetRecentHighlights(ctx context.Context, arg GetRecentHighlightsParams) ([]AllHighlight, error)
	GetRepliesByAuthor(ctx context.Context, authorDid string) ([]Reply, error)
	GetRepliesByRoot(ctx context.Context, rootUri string) ([]Reply, error)
	GetRepliesByURIs(ctx context.Context, dollar_1 []string) ([]Reply, error)
	GetReplyByURI(ctx context.Context, uri string) (Reply, error)
	GetReplyCount(ctx context.Context, rootUri string) (int64, error)
	GetReplyCounts(ctx context.Context, dollar_1 []string) ([]GetReplyCountsRow, error)
	GetReport(ctx context.Context, id int32) (ModerationReport, error)
	GetReportActions(ctx context.Context, reportID int32) ([]ModerationAction, error)
	GetReportCount(ctx context.Context) (int64, error)
	GetReportCountByStatus(ctx context.Context, status string) (int64, error)
	GetReports(ctx context.Context, arg GetReportsParams) ([]ModerationReport, error)
	GetReportsByStatus(ctx context.Context, arg GetReportsByStatusParams) ([]ModerationReport, error)
	GetSembleAnnotations(ctx context.Context, arg GetSembleAnnotationsParams) ([]AllAnnotation, error)
	GetSembleAnnotationsByAuthor(ctx context.Context, arg GetSembleAnnotationsByAuthorParams) ([]AllAnnotation, error)
	GetSembleAnnotationsByTag(ctx context.Context, arg GetSembleAnnotationsByTagParams) ([]AllAnnotation, error)
	GetSembleAnnotationsByTagAndAuthor(ctx context.Context, arg GetSembleAnnotationsByTagAndAuthorParams) ([]AllAnnotation, error)
	GetSembleBookmarks(ctx context.Context, arg GetSembleBookmarksParams) ([]AllBookmark, error)
	GetSembleBookmarksByAuthor(ctx context.Context, arg GetSembleBookmarksByAuthorParams) ([]AllBookmark, error)
	GetSembleBookmarksByTag(ctx context.Context, arg GetSembleBookmarksByTagParams) ([]AllBookmark, error)
	GetSembleBookmarksByTagAndAuthor(ctx context.Context, arg GetSembleBookmarksByTagAndAuthorParams) ([]AllBookmark, error)
	GetSembleHighlights(ctx context.Context, arg GetSembleHighlightsParams) ([]AllHighlight, error)
	GetSembleHighlightsByAuthor(ctx context.Context, arg GetSembleHighlightsByAuthorParams) ([]AllHighlight, error)
	GetSembleHighlightsByTag(ctx context.Context, arg GetSembleHighlightsByTagParams) ([]AllHighlight, error)
	GetSembleHighlightsByTagAndAuthor(ctx context.Context, arg GetSembleHighlightsByTagAndAuthorParams) ([]AllHighlight, error)
	GetShelvedAnnotations(ctx context.Context, arg GetShelvedAnnotationsParams) ([]AllAnnotation, error)
	GetShelvedBookmarks(ctx context.Context, arg GetShelvedBookmarksParams) ([]AllBookmark, error)
	GetShelvedCollectionItems(ctx context.Context, arg GetShelvedCollectionItemsParams) ([]CollectionItem, error)
	GetShelvedHighlights(ctx context.Context, arg GetShelvedHighlightsParams) ([]AllHighlight, error)
	GetTrendingTags(ctx context.Context, limit int32) ([]GetTrendingTagsRow, error)
	GetUnreadNotificationCount(ctx context.Context, recipientDid string) (int64, error)
	GetUserProfile(ctx context.Context, authorDid string) (UserProfile, error)
	GetUserTags(ctx context.Context, arg GetUserTagsParams) ([]GetUserTagsRow, error)
	GetViewerLikes(ctx context.Context, arg GetViewerLikesParams) ([]string, error)
	InsertKVIgnore(ctx context.Context, arg InsertKVIgnoreParams) error
	IsBanned(ctx context.Context, did string) (bool, error)
	IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error)
	IsBlockedEither(ctx context.Context, arg IsBlockedEitherParams) (bool, error)
	IsMuted(ctx context.Context, arg IsMutedParams) (bool, error)
	IsTakenDown(ctx context.Context, uri string) (bool, error)
	MarginNoteBookmarkExists(ctx context.Context, arg MarginNoteBookmarkExistsParams) (int32, error)
	MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error
	MarkTakenDown(ctx context.Context, arg MarkTakenDownParams) error
	MatchAnnotationToDocument(ctx context.Context, canonicalUrl *string) (string, error)
	NegateContentLabel(ctx context.Context, id int32) error
	RemoveFromCollection(ctx context.Context, uri string) error
	ResolveReport(ctx context.Context, arg ResolveReportParams) error
	SaveCommunityBookmarkRef(ctx context.Context, arg SaveCommunityBookmarkRefParams) error
	SaveEditHistory(ctx context.Context, arg SaveEditHistoryParams) error
	SavePendingAuthOAuth(ctx context.Context, arg SavePendingAuthOAuthParams) error
	UnbanAccount(ctx context.Context, did string) error
	UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error
	UpdateAnnotation(ctx context.Context, arg UpdateAnnotationParams) error
	UpdateBookmark(ctx context.Context, arg UpdateBookmarkParams) error
	UpdateHighlight(ctx context.Context, arg UpdateHighlightParams) error
	UpdateNoteAnnotation(ctx context.Context, arg UpdateNoteAnnotationParams) error
	UpdateNoteBookmark(ctx context.Context, arg UpdateNoteBookmarkParams) error
	UpdateNoteHighlight(ctx context.Context, arg UpdateNoteHighlightParams) error
	UpdateOAuthSessionTokens(ctx context.Context, arg UpdateOAuthSessionTokensParams) error
	UpsertAnnotationEmbedding(ctx context.Context, arg UpsertAnnotationEmbeddingParams) error
	UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error
	UpsertDocumentEmbedding(ctx context.Context, arg UpsertDocumentEmbeddingParams) error
	UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) error
	UpsertProfile(ctx context.Context, arg UpsertProfileParams) error
	UpsertPublication(ctx context.Context, arg UpsertPublicationParams) error
	UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) error
}

var _ Querier = (*Queries)(nil)
